# services:
#   db:
#     image: mysql
#     restart: on-failure
#     environment:
#       MYSQL_ROOT_PASSWORD: password
#       MYSQL_DATABASE: mydb
#     networks:
#       - network

#   backend:
#     restart: on-failure
#     build: ./backend
#     networks:
#       - network
#   web:
#     restart: on-failure
#     build: 
#       context: web
#     networks:
#       - network
#   nginx:
#     restart: always
#     build: ./nginx
#     ports:
#     - '80:80'
#     - '443:443'
#     volumes:
#     - ./certbot/www/:/var/www/certbot/:ro
#     depends_on:
#     - web
#     networks:
#       - network
#   certbot:
#     image: certbot/certbot:latest
#     volumes:
#       - ./certbot/www/:/var/www/certbot/:rw
#       - ./certbot/conf/:/etc/letsencrypt/:rw
#     networks:
#       - network
# networks:
#   network : 


services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www/:/var/www/certbot/:ro
    networks:
      - network
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    networks:
      - network
networks:
  network : 