services:
  db:
    image: mariadb:11.5.1-ubi9-rc
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: siliconsavannah
    networks:
      - network
  adminer:
    image: adminer
    restart: always
    networks:
      - network
  backend:
    restart: on-failure
    build: ./backend
    networks:
      - network
  web:
    restart: on-failure
    build: 
      context: web
    networks:
      - network
  caddy:
    image: caddy:2.7.6-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
      - "8080:8080"
    volumes:
      - ./caddy:/etc/caddy
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - network
volumes:
  caddy_data:
  caddy_config:
networks:
  network : 